# Dev version
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./my-expenses-ui/package.json ./my-expenses-ui/package-lock.json ./
RUN npm ci

# Copy source (in dev you might prefer mounting instead of copying)
COPY ./my-expenses-ui/ .

# Expose React dev server port
EXPOSE 3000

# Start React app
CMD ["npm", "start"]
